CREATE TABLE [dbo].[CHARACTER_ABILITY] (
    [ca_cid] INT NOT NULL,
    [ca_CHA] INT DEFAULT ((0)) NULL,
    [ca_CON] INT DEFAULT ((0)) NULL,
    [ca_DEX] INT DEFAULT ((0)) NULL,
    [ca_INT] INT DEFAULT ((0)) NULL,
    [ca_STR] INT DEFAULT ((0)) NULL,
    [ca_WIS] INT DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([ca_cid] ASC),
    CONSTRAINT [FK_CHARACTER_ABILITY_ToCHARACTER] FOREIGN KEY ([ca_cid]) REFERENCES [dbo].[CHARACTER] ([c_id])
);

