CREATE TABLE [dbo].[CHARACTER_ABILITY] (
    [ca_cid] INT NOT NULL,
	[ca_aid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ca_cid], [ca_aid]),
    CONSTRAINT [FK_CHARACTER_ABILITY_ToCHARACTER] FOREIGN KEY ([ca_cid]) REFERENCES [dbo].[CHARACTER] ([c_id]),
	CONSTRAINT [FK_CHARACTER_ABILITY_ToABILITY] FOREIGN KEY ([ca_aid]) REFERENCES [dbo].[ABILITY] ([a_id])
);

