CREATE TABLE [dbo].[EVENT_OCCURRED_TYPES] (
    [eot_eoid] INT NOT NULL,
    [eot_etid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([eot_etid] ASC, [eot_eoid] ASC),
    CONSTRAINT [FK_EVENT_OCCURRED_TYPES_ToEVENT_OCCURRED] FOREIGN KEY ([eot_eoid]) REFERENCES [dbo].[EVENT_OCCURRED] ([eo_id]),
    CONSTRAINT [FK_EVENT_OCCURRED_TYPES_ToEVENT_TYPE] FOREIGN KEY ([eot_etid]) REFERENCES [dbo].[EVENT_TYPE] ([et_id])
);

