CREATE TABLE [dbo].[ITEM_BACKGROUND] (
    [ib_iid] INT NOT NULL,
    [ib_bid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ib_bid] ASC, [ib_iid] ASC),
    CONSTRAINT [FK_ITEM_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([ib_bid]) REFERENCES [dbo].[BACKGROUND] ([b_id]),
    CONSTRAINT [FK_ITEM_BACKGROUND_ToITEM] FOREIGN KEY ([ib_iid]) REFERENCES [dbo].[ITEM] ([i_id])
);

