CREATE TABLE [dbo].[LOCATION_BACKGROUND] (
    [lb_lid] INT NOT NULL,
    [lb_bid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([lb_lid] ASC, [lb_bid] ASC),
    CONSTRAINT [FK_LOCATION_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([lb_bid]) REFERENCES [dbo].[BACKGROUND] ([b_id]),
    CONSTRAINT [FK_LOCATION_BACKGROUND_ToLOCATION] FOREIGN KEY ([lb_lid]) REFERENCES [dbo].[LOCATION] ([l_id])
);

