CREATE TABLE [dbo].[QUEST_BACKGROUND] (
    [qb_qid] INT NOT NULL,
    [qb_bid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([qb_bid] ASC, [qb_qid] ASC),
    CONSTRAINT [FK_QUEST_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([qb_bid]) REFERENCES [dbo].[BACKGROUND] ([b_id]),
    CONSTRAINT [FK_QUEST_BACKGROUND_ToQUEST] FOREIGN KEY ([qb_qid]) REFERENCES [dbo].[QUEST] ([q_id])
);

