CREATE TABLE [dbo].[CHARACTER_SKILL] (
    [cs_cid] INT NOT NULL,
    [cs_sid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([cs_sid] ASC, [cs_cid] ASC),
    CONSTRAINT [FK_CHARACTER_SKILL_ToCHARACTER] FOREIGN KEY ([cs_cid]) REFERENCES [dbo].[CHARACTER] ([c_id]),
    CONSTRAINT [FK_CHARACTER_SKILL_ToSKILL] FOREIGN KEY ([cs_sid]) REFERENCES [dbo].[SKILL] ([s_id])
);

