CREATE TABLE [dbo].[RACE_BACKGROUND] (
    [rb_rid] INT NOT NULL,
    [rb_bid] INT NOT NULL,
    CONSTRAINT [PK_RACE_BACKGROUND] PRIMARY KEY CLUSTERED ([rb_rid] ASC, [rb_bid] ASC),
    CONSTRAINT [FK_RACE_BACKGROUND_ToBACKGROUND] FOREIGN KEY ([rb_bid]) REFERENCES [dbo].[BACKGROUND] ([b_id]),
    CONSTRAINT [FK_RACE_BACKGROUND_ToRACE] FOREIGN KEY ([rb_rid]) REFERENCES [dbo].[RACE] ([r_id])
);

